import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Header/nabvar";
import AboutUs from "@/components/About Us/AboutUs";
// import { Process } from "@/components/Services/Service";
import ServiceOptions from "@/components/Services/ServiceOptions";
import Contact from "@/components/Contact/Contact";
import { Footer } from "@/components/Footer/Footer";
// import { NavBar } from "@/components/Header/menus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <AboutUs />

        <ServiceOptions />
        <Contact />
        <Footer />
      </body>
    </html>
  );
}
